# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{noguchi}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pete Hodgson"]
  s.date = %q{2010-04-05}
  s.description = %q{A simple, declarative way to display tabular data}
  s.email = %q{public@thepete.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "lib/noguchi.rb",
     "lib/noguchi/cell_data_context.rb",
     "lib/noguchi/cell_output.rb",
     "lib/noguchi/low_level_table.rb",
     "lib/noguchi/simple_table.rb",
     "lib/noguchi/table.rb",
     "lib/noguchi/version.rb"
  ]
  s.homepage = %q{http://github.com/moredip/noguchi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple, declarative way to display tabular data}
  s.test_files = [
    "spec/cell_output_spec.rb",
     "spec/csv_render_spec.rb",
     "spec/low_level_table_spec.rb",
     "spec/simple_table_spec.rb",
     "spec/spec_helper.rb",
     "spec/table_spec.rb",
     "examples/common.rb",
     "examples/csv_rendering.rb",
     "examples/editable_user.rb",
     "examples/low_level_table.rb",
     "examples/simple_hash_table.rb",
     "examples/simple_model_table.rb",
     "examples/simple_model_table_with_custom_body_cell.rb",
     "examples/simple_model_table_with_edit_link.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

